import type { Metadata } from "next";
import { alata } from "@/app/font"
import "./globals.css";
import Footer from "@/components/Footer"
import { PProvider } from "@/lib/Provider";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PProvider>
      <html lang="en">
        <body className={`${alata.className} text-[15px] relative`}>
          <Sidebar />
          {children}
          <Footer />
        </body>
      </html>
    </PProvider>
  );
}
