import type { Metadata } from "next";
import { alata } from "@/app/font"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alata.className} text-[15px]`}>{children}</body>
    </html>
  );
}
